
# 应用名称
spring:
  application:
    name: demo
# 关闭缓存引擎 (thymeleaf 缓存)
  thymeleaf:
    cache: false

#  security:
#    user:
#      name: root
#      password: root
#      roles: admin

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

# 应用服务 WEB 访问端口
server:
  port: 8080


# myBatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.security.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
#logging:
#  root:
#    level: debug
